server:
    port: 8080
  #spring:
  #  security:
  #    oauth2:
  #      resourceserver:
  #        jwt:
  #          issuer-uri: https://login.microsoftonline.com/9f5749d2-1a60-4dbd-981c-ae949f54a23d/v2.0
  #jwt:
  #  discoveryEndpoint: 'https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration'
  #  jwks: 'https://login.microsoftonline.com/common/discovery/v2.0/keys'

  # In v2.0 tokens, `aud` is always the client ID of the API, while in v1.0 tokens it can be the resource URI used in the request.

spring:
  cloud:
    azure:
# Properties like spring.cloud.azure.credential.client-id are global properties.
# Properties like spring.cloud.azure.active-directory.credential.client-id are AAD properties.
# If AAD properties is not configured, global properties will be used.
#      credential:
#        client-id:
#        client-secret:
#      profile:
#        tenant-id:
      active-directory:
        b2c:
          enabled: true
          profile:
            tenant-id: 'a6fd3216-ecef-4943-9bc8-1c06977d31d5'
          #app-id-uri: ${APP_ID_URI}         # If you are using v1.0 token, please configure app-id-uri for `aud` verification
          #credential:
            #client-id: '9c64ae71-e7b0-45d4-b507-2d50fe845084'           # If you are using v2.0 token, please configure client-id for `aud` verification
          base-uri: 'https://login.microsoftonline.com/pawel90g.onmicrosoft.com/'
          #user-flows:
            #sign-up-or-sign-in: ${SIGN_UP_OR_SIGN_IN_USER_FLOW_NAME}